### ISSUE TITLE
Add Hover Effect to Frequently Asked Questions Cards

### ISSUE THREAD

**Issue by neeru24** [subhadipbhowmik/bio-branch#119]
The Frequently Asked Questions (FAQ) cards currently lack any hover effects, making them less interactive and visually engaging. Implementing hover effects will enhance the user experience and improve the overall aesthetic of the FAQ section.

**### Proposed Changes:**

**Hover Effect Design:**

- Add a subtle scaling effect on hover to make the cards appear more dynamic.
- Change the background color slightly to indicate interactivity.
- Consider adding a shadow effect to give a sense of depth.

**CSS Implementation:**

- Use CSS transitions for smooth hover effects.
- Ensure the hover effects are responsive and work well on different screen sizes.

**Use Case**: When a user hovers over a FAQ card, they should feel an interactive response, prompting them to click for more information. This can lead to improved engagement with the FAQ content.

**Benefit**: Adding hover effects will make the FAQ section more visually appealing and interactive, enhancing the overall user experience and encouraging users to explore the FAQs more thoroughly.

Could you please assign me this issue? I’m excited to implement these changes and will submit a PR shortly after completing the enhancements.

Thank you!
![image](https://github.com/user-attachments/assets/162e2186-9ca3-4306-b5ff-53667354a560)

**Comment by arduvey29** [comment]
Hi, I’d love to help resolve this issue—could you please assign it to me? @subhadipbhowmik

**Comment by neeru24** [comment]
> The Frequently Asked Questions (FAQ) cards currently lack any hover effects, making them less interactive and visually engaging. Implementing hover effects will enhance the user experience and improve the overall aesthetic of the FAQ section.
> 
> **### Proposed Changes:**
> 
> **Hover Effect Design:**
> 
> * Add a subtle scaling effect on hover to make the cards appear more dynamic.
> * Change the background color slightly to indicate interactivity.
> * Consider adding a shadow effect to give a sense of depth.
> 
> **CSS Implementation:**
> 
> * Use CSS transitions for smooth hover effects.
> * Ensure the hover effects are responsive and work well on different screen sizes.
> 
> **Use Case**: When a user hovers over a FAQ card, they should feel an interactive response, prompting them to click for more information. This can lead to improved engagement with the FAQ content.
> 
> **Benefit**: Adding hover effects will make the FAQ section more visually appealing and interactive, enhancing the overall user experience and encouraging users to explore the FAQs more thoroughly.
> 
> Could you please assign me this issue? I’m excited to implement these changes and will submit a PR shortly after completing the enhancements.
> 
> Thank you! ![image](https://private-user-images.githubusercontent.com/161798182/374872674-162e2186-9ca3-4306-b5ff-53667354a560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDYyNDYsIm5iZiI6MTcyODgwNTk0NiwicGF0aCI6Ii8xNjE3OTgxODIvMzc0ODcyNjc0LTE2MmUyMTg2LTljYTMtNDMwNi1iNWZmLTUzNjY3MzU0YTU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNzUyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjQyOTlmZjQ3MTVlMGJhYWQ5MmRlNzUyZmYxZmZmNWRmMDMyN2I1MDQ1ZmE4YWVjYTYwNzczMTdlNTcyMDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3lY2x8xMoQME7oSlYT8hKAT3y44NUcRbEMLUq1e25sk)

Kindly check it @subhadipbhowmik
