### ISSUE TITLE
Add Hover Effect to How to Join Bio Tree Cards

### ISSUE THREAD

**Issue by Nitish6391920700** [subhadipbhowmik/bio-branch#124]
Add Hover Effect to How to Join Bio Tree Cards

**Comment by Nitish6391920700** [comment]
Add Hover Effect  How to Join Bio Tree Cards

**Comment by meghanakn473** [comment]
@subhadipbhowmik can u assign me this issue

**Comment by meghanakn473** [comment]
@subhadipbhowmik please review and merge , i hv made pr
