### ISSUE TITLE
sign in through google

### ISSUE THREAD

**Issue by meghanakn473** [subhadipbhowmik/bio-branch#139]
registering through email username password might not be choice of everyone. 
so making a one step easy i want add the option of sign through google account directly

@subhadipbhowmik please assign me this task

**Comment by subhadipbhowmik** [comment]
@meghanakn473 

Thank you for your patience. We have assigned you to integrate Google SSO. Looking forward to your pull request.

**Comment by meghanakn473** [comment]
@subhadipbhowmik please assign level 3 bcz i need to fix frontend backend and authentication from google cloud

**Comment by meghanakn473** [comment]
@subhadipbhowmik can u provide me .env file api keys for below
GOOGLE_CLIENT_ID=your_google_client_id
JWT_SECRET=your_secret_key

so that i can make pr with proof
completed my code implementation

**Comment by meghanakn473** [comment]
@subhadipbhowmik 
wen i click on the signin with google in the register page of app then it comes like this, 
wen i inspected the page, the console says the client id is not found, 
but actually i created project for this and set up the client id in google cloud 

![Screenshot (166)](https://github.com/user-attachments/assets/b486e7a8-087e-4855-9285-ce6f3dfe741e)

wt shd i do ? @subhadipbhowmik please guide me
