### ISSUE TITLE
Adding newsletter section 

### ISSUE THREAD

**Issue by ThunderShadows** [subhadipbhowmik/bio-branch#142]
The newsletter section in the website is missing. It is required for the users to be updated about the latest trends in the website and get notified by the website in their emails.

@subhadipbhowmik 

I shall include a newsletter submission form for the users to input their names and their email id for the subscription of Bio Branch Website.

**Comment by meghanakn473** [comment]
@subhadipbhowmik i would like to work on it and also add confirmation message to users wen once the user subscribed to it
please assign me this issue

**Comment by meghanakn473** [comment]
@subhadipbhowmik done !! please check and allow merge
