### ISSUE TITLE
Add Translation Tool 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [subhadipbhowmik/bio-branch#224]
I want to add a Translation Tool(all language) properly.

@subhadipbhowmik PA please assign me this task.

![Screenshot 2024-10-16 121229](https://github.com/user-attachments/assets/f4409eb2-7bb9-4a56-8b86-0082e964d20f)

**Comment by Subhajit-2023-44** [comment]
@subhadipbhowmik

**Comment by subhadipbhowmik** [comment]
I think these are not as important for this site.

**Comment by Subhajit-2023-44** [comment]
> I think these are not as important for this site.

Can i add a contributors page ??
