### ISSUE TITLE
top to scroll button

### ISSUE THREAD

**Issue by meghanakn473** [subhadipbhowmik/bio-branch#331]
### Is your proposal related to a problem?

Its a feature which helps user to navigate to top of page easily

### Describe the solution you'd like

i would like to add a top arrow button in the bottom right corner of page

@subhadipbhowmik please assign me this issue at level 3, gssoc-extd

**Comment by meghanakn473** [comment]
hey @subhadipbhowmik please assign level 2/3, i hope ull consider it

**Comment by ashutoshak5386** [comment]
can you please assign this issue to me i would like to work on it.

**Comment by meghanakn473** [comment]
> can you please assign this issue to me i would like to work on it.

Already pr is made @ashutoshak5386
