### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by srajangupta144** [subhadipbhowmik/bio-branch#351]
I would like to propose the addition of a dark mode feature to enhance the user experience for our project. Dark mode has become increasingly popular due to its aesthetic appeal and potential benefits for users, including reduced eye strain and improved readability in low-light environments. Implementing a dark mode option will provide users with greater flexibility in how they interact with the application, catering to personal preferences and enhancing accessibility.

By allowing users to toggle between light and dark themes, we can create a more inclusive experience that accommodates a wider range of visual needs. This feature is particularly relevant for users who spend extended periods working with the application, as it can help minimize fatigue and create a more comfortable viewing environment. I believe that integrating dark mode will not only improve overall user satisfaction but also align our project with modern design standards and user expectations. Thank you for considering this enhancement!

**Comment by meghanakn473** [comment]
@subhadipbhowmik please assign this issue to me as there is no response from @srajangupta144
