### ISSUE TITLE
Enhance : Adding shadow effect upon hover to "Features" Cards

### ISSUE THREAD

**Issue by iamsaura8h** [subhadipbhowmik/bio-branch#7]
hey @subhadipbhowmik , 

I would like to add shadow effects on top of hover to increase user ui/ux for your website.
<img width="960" alt="is3" src="https://github.com/user-attachments/assets/5e99a029-074e-4aef-9c85-088cf252a13d">

### please assign me this issue with gssoc-ext label

**Comment by pameladeysarkar2003** [comment]
please assign me with this task @subhadipbhowmik
